language: java
dist: trusty

jdk:
  - openjdk8
  - openjdk11

env:
  - HADOOP_PROFILE=default TEST_CODECS=uncompressed,brotli
  - HADOOP_PROFILE=default TEST_CODECS=gzip,snappy

before_install:
  - bash dev/travis-before_install.sh
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install: mvn install --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -Dsource.skip=true | pv -fbi 60 > mvn_install.log || (cat mvn_install.log && false)

jobs:
  include:
    - stage: test
      name: "Check"
      script: mvn verify --batch-mode javadoc:javadoc -P travis,$HADOOP_PROFILE
    - stage: publish
#      if: branch = nexus-release
      name: "Publish"
      script: mvn deploy --settings `pwd`/settings.xml -DskipTests=true
#      on:
#        tags: true
